# Probability
## Introduction to Probabilities
In 1814, Pierre-Simon Laplace wrote:  
> Probability theory is nothing but common sense reduced to calculation. 
... [Probability] is thus simply a fraction whose numerator is the 
number of favorable cases and whose denominator is the number of all 
the cases possible ... when nothing leads us to expect that any one of 
these cases should occur more than any other.
Laplace nailed it. To untangle a probability problem, all you have to do 
is define exactly what the cases are, and careful count the favorable 
and total cases. Let's be clear on our vocabulary words:
- **Trial**
A single occurrence with an outcome that is uncertain until we observe it.  
*For example, rolling a single die.*
- **Outcome**
A possible result of a trial; one particular state of the world. What 
Laplace calls a **case.** *For example:* `4`.
- **Sample Space**
The set of all possible outcomes for the trial.   
*For example,* `{1, 2, 3, 4, 5, 6}`.
- **Event**
A subset of the sample space, a set of outcomes that together have some 
property we are interested in.  
*For example, the event "even die roll" is the set of outcomes* 
`{2, 4, 6}`.
- **Probability**
As Laplace said, the probability of an event with respect to a sample 
space is the "number of favorable cases" (outcomes from the sample space 
that are in the event) divided by the "number of all the cases" in the 
sample space (assuming "nothing leads us to expect that any one of these 
cases should occur more than any other"). Since this is a proper 
fraction, probability will always be a number between 0 (representing an 
impossible event) and 1 (representing a certain event).  
*For example, the probability of an even die roll is 3/6 = 1/2.*

In [1]:
import random # generador de números aleatorios
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
#1.Generación de lanzamientos de una moneda, sello = o, cara = 1
toss = random.randint(0,1)
print(toss)


1


In [6]:
#2 Generación de lanzamientos de monedas con una estructura de control for, if, while
toss_results = []
for i in range (10):
    result = random.randint(0,1)
    toss_results.append(result)
print(toss_results)

[0, 0, 0, 0, 0, 1, 1, 1, 0, 1]


In [7]:
#3. Generación de lanzamiento de monedas controlado para ser reproducible
random.seed(2024)
toss_results = []
for i in range (10):
    result = random.randint(0,1)
    toss_results.append(result)
print(toss_results)

[1, 0, 1, 0, 1, 1, 0, 1, 1, 1]


In [10]:
#4. Calcular la probabilidad de que salga cara en 10 lanzamientos de moneda
toss_results = []
for i in range (10):
    result = random.randint(0,1)
    toss_results.append(result)
print(toss_results)
sum(toss_results)/len(toss_results) #Calcular la probabilidad sin necesidad de sumar a mano

[1, 1, 1, 1, 0, 1, 0, 0, 0, 0]


0.5

In [11]:
#4. Calcular la probabilidad de que salga cara en 10 lanzamientos de moneda
toss_results = []
for i in range (1000000):
    result = random.randint(0,1)
    toss_results.append(result)
#print(toss_results)
sum(toss_results)/len(toss_results)

0.499503

In [12]:
from fractions import Fraction 

In [14]:
Fraction(1,3) #es un tipo de dato para representar un fracción en python

Fraction(1, 3)

In [15]:
#2 Calcular probabilidad de sacar par en un lanzamiento de dados
even = {2,4,6}
points = {1,2,3,4,5,6} #Asumimos que el dado esta perfectamente balanceado
set.intersection(even,points)

{2, 4, 6}

In [16]:
def Pr(event,space):
    return Fraction(len(set.intersection(even,space)),len(space))

In [17]:
Pr(even,points)

Fraction(1, 2)

In [19]:
#Calcular la probabilidad de obtener cinco o seis en un lanzamiento de dados
succes = {5,6}
points = {1,2,3,4,5,6}
Pr(succes,points)

Fraction(1, 2)

In [21]:
#This refers to a discrete sample space, so the probability is related to a discrete event

In [27]:
# box1 = [1,0,0,0] #La probabilidad de éxito es de 1/4 = 0,25
# box2 = [1,1,0,0,0] #La probabilidad de éxito es de 2/5 = 0.4
box1 = np.array([1,0,0,0]) #Este es un vector ([])
np.random.choice(box1,1) #Simula el evento de sacar una piedra

array([1])

In [31]:
trial = np.random.choice(box1,100000)
trial.mean()

np.float64(0.24986)

In [32]:
box2 = np.array([1,0,1,0,0])
trial = np.random.choice(box2,100000)
trial.mean() #Aquí funciona mean()porque solo hay dos resultados 0 y 1 y además el resultado exitoso es 1

np.float64(0.39997)

In [ ]:
#Cuando son mas de dos resultados
success = np.isin(trial,[1])
probability = len(trial[success])/len(trial)

In [40]:
np.random.seed(2024)
yankenpo = np.array([1,2,3])
trial = np.random.choice(yankenpo,10)
success = np.isin(trial,[2]) #isin nos retorna un vector de booleanos
probability = len(trial[success])/len(trial)
probability

0.2

In [37]:
yankenpo
trial
success

array([False, False, False,  True, False, False, False,  True, False,
       False])

In [38]:
trial

array([1, 3, 3, 2, 1, 1, 3, 2, 3, 3])

In [39]:
trial[success] #Esto es lo que se conoce como mascara, solo devuelve los casos de exito

array([2, 2])

In [41]:
results = np.array([14,22,21,15,18,23,19])
success = np.isin(results,[21])
results[success]

array([21])

In [46]:
#3 El siquiente problema muestra la probabilidad condicional
#Cuál es la probabilidad de sacar un As en una segunda extracción si en la primera estracción ya saque un As
#Cuántos ases hay en un baraja: 4
#Cuántps naipes hay en una baraja: 52
#Cuál es la probabilidad de sacar en la primera extracción un As: 4/52 = 1/13
#Si ya saqué un As de la baraja, Cuántos naipes me quedan: 51 y 3 Ases
#En una seguna extracción, la probabilidad de sacar un As sería: Pr(Sacar As en segunda extracción dado que se sacó un as en la primera extracción)
#Por lo tanto, esto quiere decir que esta probabilidad esta condicionada al evento de haber sacado un As en la primera extración
#la fórmula para calcularlo sería Pr=3/51
#Pr(A and B) = Pr(A)*Pr(B|A)
#Si A y B son Independientes entonces Pr(A|B) = Pr(A)
#Pr( A and B and C) = Pr(A)*Pr(B|A)*Pr(C|A and B) Regla de la cadena
#Pr (A or B) = Pr(A)+Pr(B)-Pr(A and B)
#En un avión hay 3 bombas, cada bomba tiene 0.4 probabilidades de explotar, entonces cuál es la probabilidad de que la segúnda bomba explote
#Cuál es la probabilidad de que las tres bombas exploten Pr(A and B and C)= Pr(A)*Pr(B)*Pr(c) = 0.4*0.4*0.4
#Cuál es la probabilidad de que en una sala con 10 personas dos cumplan años el mismo día. Y en una sala con 20 personas y en una sala con 30 personas y en una sala con 50 personas
def same_birthday(n):
    days = np.linspace(1,366,)
    bday = np.random.choice(days,n)
    return np.any(np.bincount(bday)>1)
same_birthday(10)

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In [44]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
def same_birthday(n):
    days = np.arange(1,366,)
    bday = np.random.choice(days,n)
    return np.any(np.bincount(bday)>1)
same_birthday(10)
counter = 0
for i in range (10000):
if same_birthday(10):
    counter +=1
counter/10000

IndentationError: expected an indented block after 'for' statement on line 7 (1401378940.py, line 8)